# This is a sample aws-auth-patch.yml file.
# Actual aws-auth-patch.yml will be created at /System/Volumes/Data/private/tmp/aws-auth-patch.yml path.
apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:masters
      rolearn: arn:aws:iam::583512838944:role/UdacityFlaskDeployCBKubectlRole
      username: build
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::583512838944:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-1BA9VTPN8CSYE
      username: system:node:{{EC2PrivateDNSName}}
kind: ConfigMap
metadata:
  creationTimestamp: "2021-08-20T02:45:55Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1286"
  uid: e7111693-4d2f-4847-8659-88d0f532cb81
